name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: pyinstaller creeper.py
      - run: cp -r assets dist/creeper
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: creeper-${{ matrix.os }}
          path: dist
  build-site:
    needs: release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: creeper-windows-latest
          path: static
      - uses: actions/download-artifact@v3
        with:
          name: creeper-ubuntu-latest
          path: static
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install hatch
        run: pip install hatch
      - name: build with markata
        run: hatch run build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          # you can choose the target branch of your choice
          target_branch: prod-markata
          build_dir: markout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
